from flask import Flask

app: Flask

@app.route('/')
def home(): ...
@app.route('/api/auth')
def auth_root(): ...
@app.route('/api/auth/callback')
def auth_callback(): ...
@app.route('/api/auth/logout')
def auth_logout(): ...
@app.route('/api/me')
def me(): ...
@app.route('/api/recommendations')
def api_get_recommendations(): ...
@app.route('/api/recommendations', methods=['POST'])
def api_post_recommendations(): ...
@app.route('/api/recommendations/{id}', methods=['PATCH'])
def api_patch_recommendation(id: str): ...
@app.route('/api/recommendations/{id}', methods=['DELETE'])
def api_delete_recommendation(id: str): ...
@app.route('/api/recommendations/{id}/votes', methods=['POST'])
def api_post_recommendation_votes(id: str): ...
